# 推荐阅读 https://book.sotap.org/#/ageing/config 来阅读每一项的具体含义
# 达到一定年龄后所要执行的命令
# 对于 0，代表玩家安装插件后第一次入服时执行的命令
age_commands:
  "0":
  - say Welcome! %playername%
# 用户可以达到的最大年龄数值
max_age: 100
# 受到年龄限制的指令
limited_commands:
  example: 0
# 能够使用指令的最低年龄
command_lowest_limit: 0
# 不受年龄限制的指令
ignored_commands:
  - "example"
# 年龄增长所需经验值的基础值
# 参考 https://book.sotap.org/#/ageing/growth
growth_base_value: 200
# 年龄增长所需经验值的叠加值
growth_step_value: 150
# 年龄增长的基本区间长度
growth_range_length: 5
# 是否开启另一套等级系统
enable_levels: false