name: Ageing
main: org.sotap.Ageing.Ageing
version: "1.0"
author: sotapmc
api-version: "1.16"
softdepend:
  - PlaceholderAPI

commands:
  ageing:
    aliases: ["age"]
    description: Controls the Ageing plugin.
    permission: ageing.command
    permission-message: "You do not have the permission to use the command."
    usage: /age <options>
permissions:
  ageing.all:
    description: The super permission node for Ageing.
    default: op
    children:
      ageing.set: true
      ageing.get: true 
      ageing.add: true
      ageing.sub: true
      ageing.setexp: true
      ageing.addexp: true
      ageing.subexp: true
      ageing.getexp: true
      ageing.reload: true
      ageing.me: true
  ageing.set:
    default: op
  ageing.get:
    default: op
  ageing.add:
    default: op
  ageing.sub:
    default: op
  ageing.setexp:
    default: op
  ageing.addexp:
    default: op
  ageing.subexp:
    default: op
  ageing.getexp:
    default: op
  ageing.reload:
    default: op
  ageing.me:
    default: true